env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  import/no-dynamic-require: 1
  class-methods-use-this: 0
  max-len: 0
  no-underscore-dangle: 0
  no-plusplus: [error, {allowForLoopAfterthoughts: true}]
  consistent-return: 0
  no-await-in-loop: 0
  no-restricted-syntax: 0
  no-param-reassign: 0
  no-console: 0
  camelcase: 0