# MerMer Default Config

title = "TidetimeBridge"

[base]
folder = "TidetimeBridge"
static = "./build/frontend/"
debug = false

[blockchain.base]
type = "ethereum"
tokenManagerAddress = ''
addressMappingAddress = ''
blockchainId = 'F000003C'
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[blockchain.ethereum_ropsten]
blockchainId = "F000003C"
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[blockchain.tidetime]
blockchainId = "80001F51"
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[blockchain.bitcoin_testnet]
blockchain_id = "F0000000"
protocol = "http:"
hostname = "127.0.0.1"
port = ""
path = "/"
user = ''
password = ''

[database]
type = "firebase"

[tidewalletjs]
apiURL = 'https://staging.tidewallet.io/api/v1'
apiKey = ''
apiSecret = ''
thirdPartyId = 'myAppleID'
installId = 'myInstallID'
debugMode = true
networkPublish = false

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/v1/receivedAddress | Bot.Bridge.receivedAddress",
  "post | /api/v1/registDeposit/blockchainId/:blockchainId/address/:address | Bot.Bridge.registDeposit",
  "post | /api/v1/registWithdraw/blockchainId/:blockchainId/fromAddress/:fromAddress | Bot.Bridge.registWithdraw"
]