# MerMer Default Config

title = "TidetimeBridge"

[base]
folder = "TidetimeBridge"
static = "./build/frontend/"
debug = false

[blockchain.base]
type = "ethereum"
tokenManagerAddress = ''
blockchainId = 'F000003C'
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[blockchain.ethereum_ropsten]
blockchainId = "F000003C"
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[blockchain.tidetime]
blockchainId = "80001F51"
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[database]
type = "firebase"

[tidewalletjs]
apiURL = 'https://staging.tidewallet.io/api/v1'
apiKey = ''
apiSecret = ''
thirdPartyId = 'myAppleID'
installId = 'myInstallID'
debugMode = true
networkPublish = false

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/v1/receivedAddress | Bot.Bridge.receivedAddress"
]