# MerMer Default Config

title = "TidetimeBridge"

[base]
folder = "TidetimeBridge"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo"
]