# MerMer Default Config

title = "TidetimeBridge"

[base]
folder = "TidetimeBridge"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"
blockchainId = 'F000003C'
tokenManagerAddress = ''

[database]
type = "firebase"

[tidewalletjs]
apiURL = 'https://staging.tidewallet.io/api/v1'
apiKey = ''
apiSecret = ''
thirdPartyId = 'myAppleID'
installId = 'myInstallID'
debugMode = true
networkPublish = false

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/v1/receivedAddress | Bot.Bridge.receivedAddress"
]